apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 244360367144.dkr.ecr.us-east-1.amazonaws.com/rockset-assignment:latest
          ports:
            - containerPort: 8080
