apiVersion: v1
kind: Service
metadata:
  name: py-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
#  clusterIP: 172.20.0.1
  type: LoadBalancer
